networks:
  ros: {}
services:
  all:
    command: bash -c "cd src/planner/launch && ros2 launch planner planning.launch.py"
    image: planner_nodes
    networks:
    - ros
    environment:
    - REPLAN=True
    - PROBLEM_RATE=10
  # arm:
  #   command: ros2 run planner arm
  #   image: planner_nodes
  #   networks:
  #   - ros
  # coordinator:
  #   command: ros2 run planner coordinator True
  #   image: planner_nodes
  #   networks:
  #   - ros
  # environment:
  #   command: ros2 run planner environment 10
  #   image: planner_nodes
  #   networks:
  #   - ros
  # nurse:
  #   command: ros2 run planner nurse
  #   image: planner_nodes
  #   networks:
  #   - ros
  # planner:
  #   command: ros2 run planner planner
  #   image: planner_nodes
  #   networks:
  #   - ros
  # robot:
  #   command: ros2 run planner robot
  #   image: planner_nodes
  #   networks:
  #   - ros
version: '2.3'
