networks:
  ros: {}
services:
  all:
    command: bash -c "cd src/planner/launch && ros2 launch planner planning.launch.py"
    environment:
    - REPLAN=False
    - PROBLEM_RATE=10
    image: planner_nodes
    networks:
    - ros
  controller:
    command: ros2 run labsample_plansys2 controller_node --ros-args -p "replan:=False" -p problem_rate:=10
    image: planner_nodes
    networks:
    - ros
  plansys2:
    command: ros2 launch labsample_plansys2 planning.launch.py
    environment:
    - REPLAN=False
    - PROBLEM_RATE=10
    image: planner_nodes
    networks:
    - ros
  popf:
    command: ros2 run popf popf ./src/domain-3.pddl ./src/problem-3.pddl
    image: planner_nodes
    networks:
    - ros
version: '2.3'
